### ISSUE TITLE
Implement `If-Modified-Since` support

### ISSUE THREAD

**Issue by eapl-gemugami** [sorenpeter/twtAgent#1]
To be compatible with [Clients only downloading content if it's newer](https://github.com/sorenpeter/timeline/issues/10), this Agent needs to support `If-Modified-Since` header, as Web servers like Nginx or Apache do.

# Symptom
The Agent doesn't support `If-Modified-Since` header in the request, returning the whole content anyway with HTTP code 200.

We could replicate it following this guide: [Download File only when Changed using wget/curl](https://taoshu.in/net/http-download-only-changed-using-wget-or-curl.html)

```bash
wget --debug -N https://darch.dk/twtAgent.php
```

# Expected
It should return the `Last-Modified` header with the actual file date and a [304 Not modified](https://www.siteground.com/kb/304-status-code/) status if file is older.

**Comment by eapl-gemugami** [comment]
I could help with this during the week, if it's something useful.

**Comment by sorenpeter** [comment]
Yes, having a quicker refresh would be nice. And would great to not spam other servers with requests if nothing is new.

I have also notices that some feeds are automatic updated without pressing /refresh - It that feature you made in the orignial twtxt-php, because I don't think it worked like that in the beginning?

(EDIT: I just notice that this is on twtAgent and not on Timeline)

**Comment by eapl-gemugami** [comment]
> Yes, having a quicker refresh would be nice. And would great to not spam other servers with requests if nothing is new.

Cool :D

> I have also notices that some feeds are automatic updated without pressing /refresh - It that feature you made in the orignial twtxt-php, because I don't think it worked like that in the beginning?

It wasn't me! I thought it was you :)
